name: zan_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  cookie_jar: ^3.0.1
  dio_cookie_manager: ^2.1.1
  zan_cloud_music_api:
    path: ../../../ice6/zan_cloud_music_api
#    git:
#      url: https://github.com/boyan01/NeteaseCloudMusicApi.git
#      ref: 47684bc8b75bf37ad3201993a9e3db0b5fe64ec3
  json_annotation: ^4.3.0
  async: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.5
  json_serializable: ^6.0.1
  test: ^1.21.4
  lints: ^2.0.0
